import { BsShare } from "react-icons/bs";
import { MdFavoriteBorder } from "react-icons/md";
import prodcut4 from "../../assests/images/product4.png";
import prodcut5 from "../../assests/images/product5.png";
import prodcut6 from "../../assests/images/product6.png";
import prodcut7 from "../../assests/images/product7.png";

export const recomdedData = [
  {
    id: 1,
    share: <BsShare />,
    wishList: <MdFavoriteBorder />,
    img: prodcut4,
    title: "Pantene Shampoo",
    price: "350",
    descImg1: prodcut4,
    descImg2: prodcut4,
    descImg3: prodcut4,
    descImg4: prodcut4,
    benefits1: "Stronger hair",
    benefits2: "Smoother hair & Shinier hair",
    benefits3: "Healthier hair & Damage repair",
    benefits4: "Moisture balance & Scalp nourishment",
  },
  {
    id: 2,
    share: <BsShare />,
    wishList: <MdFavoriteBorder />,
    img: prodcut5,
    title: "Pantene Shampoo",
    price: "350",
    descImg1: prodcut5,
    descImg2: prodcut5,
    descImg3: prodcut5,
    descImg4: prodcut5,
    benefits1: "Stronger hair",
    benefits2: "Smoother hair & Shinier hair",
    benefits3: "Healthier hair & Damage repair",
    benefits4: "Moisture balance & Scalp nourishment",
  },
  {
    id: 3,
    share: <BsShare />,
    wishList: <MdFavoriteBorder />,
    img: prodcut6,
    title: "Pantene Shampoo",
    price: "350",
    descImg1: prodcut6,
    descImg2: prodcut6,
    descImg3: prodcut6,
    descImg4: prodcut6,
    benefits1: "Stronger hair",
    benefits2: "Smoother hair & Shinier hair",
    benefits3: "Healthier hair & Damage repair",
    benefits4: "Moisture balance & Scalp nourishment",
  },
  {
    id: 3,
    share: <BsShare />,
    wishList: <MdFavoriteBorder />,
    img: prodcut7,
    title: "Pantene Shampoo",
    price: "350",
    descImg1: prodcut7,
    descImg2: prodcut7,
    descImg3: prodcut7,
    descImg4: prodcut7,
    benefits1: "Stronger hair",
    benefits2: "Smoother hair & Shinier hair",
    benefits3: "Healthier hair & Damage repair",
    benefits4: "Moisture balance & Scalp nourishment",
  },
];
